apiVersion: v1
kind: Service
metadata:
  name: flask-hello
  labels:
    app: flask-hello
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 31000
    targetPort: 5000
  selector:
    app: flask-hello